# Generated by Django 4.2.9 on 2025-10-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_setup_date',
            field=models.DateField(blank=True, help_text='Date when this account was created with its initial balance', null=True),
        ),
    ]
