# Generated by Django 4.2.9 on 2025-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_bankaccount_account_setup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The initial balance when the account was set up', max_digits=12),
        ),
    ]
