# Generated by Django 4.2.9 on 2025-10-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_tag_expense_tags_income_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#6366f1', 'Indigo'), ('#3b82f6', 'Blue'), ('#10b981', 'Green'), ('#f59e0b', 'Amber'), ('#ef4444', 'Red'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink'), ('#06b6d4', 'Cyan'), ('#84cc16', 'Lime'), ('#f97316', 'Orange')], default='#6366f1', max_length=7),
        ),
    ]
