version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: budget_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-budget_db}
      POSTGRES_USER: ${POSTGRES_USER:-budget_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CHANGE_ME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: budget_web
    command: gunicorn budget_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-True}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-CHANGE_ME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-CHANGE_ME}
      - DB_NAME=${DB_NAME:-budget_db}
      - DB_USER=${DB_USER:-budget_user}
      - DB_PASSWORD=${DB_PASSWORD:-CHANGE_ME}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume:

