{{- if .Values.app.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-media-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    type: media
    {{- include "budget-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.mediaSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-static-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    type: static
    {{- include "budget-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.staticSize }}
{{- end }}

