apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "budget-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.app.env.djangoSecretKey | quote }}
  # PostgreSQL environment variables
  POSTGRES_DB: {{ .Values.postgres.env.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.env.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.password | quote }}
  # Django database settings (same as PostgreSQL)
  DB_NAME: {{ .Values.postgres.env.database | quote }}
  DB_USER: {{ .Values.postgres.env.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.env.password | quote }}
  # Database URL for convenience
  DATABASE_URL: "postgresql://{{ .Values.postgres.env.user }}:{{ .Values.postgres.env.password }}@{{ .Values.postgres.name }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.env.database }}"
  {{- if .Values.app.superuser.enabled }}
  # Superuser credentials
  DJANGO_SUPERUSER_USERNAME: {{ .Values.app.superuser.username | quote }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.app.superuser.email | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.app.superuser.password | quote }}
  {{- end }}

